//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTranslatorImportTranslationsClient.TinyTranslatorSyncService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TinyTranslatorSyncService.ITinyTranslatorSyncService")]
    public interface ITinyTranslatorSyncService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorSyncService/GetProjects", ReplyAction="http://tempuri.org/ITinyTranslatorSyncService/GetProjectsResponse")]
        System.Collections.Generic.List<TinyTranslatorApplicationServer.Model.Project> GetProjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorSyncService/SyncResourceAssembly", ReplyAction="http://tempuri.org/ITinyTranslatorSyncService/SyncResourceAssemblyResponse")]
        TinyTranslatorApplicationServer.Model.ResourceSyncStatistics SyncResourceAssembly(TinyTranslatorApplicationServer.Model.ResourceAssembly ra, System.Collections.Generic.List<TinyTranslatorApplicationServer.Model.ResourceBundle> bundles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorSyncService/SyncBundles", ReplyAction="http://tempuri.org/ITinyTranslatorSyncService/SyncBundlesResponse")]
        TinyTranslatorApplicationServer.Model.ResourceSyncStatistics SyncBundles(TinyTranslatorApplicationServer.Model.ResourceAssembly ra, System.Collections.Generic.List<TinyTranslatorApplicationServer.Model.ResourceBundle> bundles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorSyncService/SyncBundleDeletions", ReplyAction="http://tempuri.org/ITinyTranslatorSyncService/SyncBundleDeletionsResponse")]
        TinyTranslatorApplicationServer.Model.ResourceSyncStatistics SyncBundleDeletions(TinyTranslatorApplicationServer.Model.ResourceAssembly ra, System.Collections.Generic.List<string> existingBundleNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorSyncService/SyncTranslations", ReplyAction="http://tempuri.org/ITinyTranslatorSyncService/SyncTranslationsResponse")]
        TinyTranslatorApplicationServer.Model.TranslationSyncStatistics SyncTranslations(TinyTranslatorApplicationServer.Model.ResourceAssembly assembly, TinyTranslatorApplicationServer.Model.ResourceBundle bundle, System.Collections.Generic.List<TinyTranslatorApplicationServer.Model.ResourceTranslation> translations);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITinyTranslatorSyncServiceChannel : TinyTranslatorImportTranslationsClient.TinyTranslatorSyncService.ITinyTranslatorSyncService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TinyTranslatorSyncServiceClient : System.ServiceModel.ClientBase<TinyTranslatorImportTranslationsClient.TinyTranslatorSyncService.ITinyTranslatorSyncService>, TinyTranslatorImportTranslationsClient.TinyTranslatorSyncService.ITinyTranslatorSyncService {
        
        public TinyTranslatorSyncServiceClient() {
        }
        
        public TinyTranslatorSyncServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TinyTranslatorSyncServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TinyTranslatorSyncServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TinyTranslatorSyncServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<TinyTranslatorApplicationServer.Model.Project> GetProjects() {
            return base.Channel.GetProjects();
        }
        
        public TinyTranslatorApplicationServer.Model.ResourceSyncStatistics SyncResourceAssembly(TinyTranslatorApplicationServer.Model.ResourceAssembly ra, System.Collections.Generic.List<TinyTranslatorApplicationServer.Model.ResourceBundle> bundles) {
            return base.Channel.SyncResourceAssembly(ra, bundles);
        }
        
        public TinyTranslatorApplicationServer.Model.ResourceSyncStatistics SyncBundles(TinyTranslatorApplicationServer.Model.ResourceAssembly ra, System.Collections.Generic.List<TinyTranslatorApplicationServer.Model.ResourceBundle> bundles) {
            return base.Channel.SyncBundles(ra, bundles);
        }
        
        public TinyTranslatorApplicationServer.Model.ResourceSyncStatistics SyncBundleDeletions(TinyTranslatorApplicationServer.Model.ResourceAssembly ra, System.Collections.Generic.List<string> existingBundleNames) {
            return base.Channel.SyncBundleDeletions(ra, existingBundleNames);
        }
        
        public TinyTranslatorApplicationServer.Model.TranslationSyncStatistics SyncTranslations(TinyTranslatorApplicationServer.Model.ResourceAssembly assembly, TinyTranslatorApplicationServer.Model.ResourceBundle bundle, System.Collections.Generic.List<TinyTranslatorApplicationServer.Model.ResourceTranslation> translations) {
            return base.Channel.SyncTranslations(assembly, bundle, translations);
        }
    }
}
