//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    [System.SerializableAttribute()]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectLocaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ProjectLocale> TranslationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectLocale {
            get {
                return this.ProjectLocaleField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectLocaleField, value) != true)) {
                    this.ProjectLocaleField = value;
                    this.RaisePropertyChanged("ProjectLocale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ProjectLocale> Translations {
            get {
                return this.TranslationsField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslationsField, value) != true)) {
                    this.TranslationsField = value;
                    this.RaisePropertyChanged("Translations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectLocale", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    [System.SerializableAttribute()]
    public partial class ProjectLocale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocaleCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocaleCode {
            get {
                return this.LocaleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocaleCodeField, value) != true)) {
                    this.LocaleCodeField = value;
                    this.RaisePropertyChanged("LocaleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceBundle", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    [System.SerializableAttribute()]
    public partial class ResourceBundle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.BundleSyncStatus BundleSyncStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastChangeDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceAssembly ResourceAssemblyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResourceAssemblyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.Resource> ResourcesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.TranslationStatus WorstTranslationStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.BundleSyncStatus BundleSyncStatus {
            get {
                return this.BundleSyncStatusField;
            }
            set {
                if ((this.BundleSyncStatusField.Equals(value) != true)) {
                    this.BundleSyncStatusField = value;
                    this.RaisePropertyChanged("BundleSyncStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDateTime {
            get {
                return this.CreateDateTimeField;
            }
            set {
                if ((this.CreateDateTimeField.Equals(value) != true)) {
                    this.CreateDateTimeField = value;
                    this.RaisePropertyChanged("CreateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastChangeDateTime {
            get {
                return this.LastChangeDateTimeField;
            }
            set {
                if ((this.LastChangeDateTimeField.Equals(value) != true)) {
                    this.LastChangeDateTimeField = value;
                    this.RaisePropertyChanged("LastChangeDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceAssembly ResourceAssembly {
            get {
                return this.ResourceAssemblyField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceAssemblyField, value) != true)) {
                    this.ResourceAssemblyField = value;
                    this.RaisePropertyChanged("ResourceAssembly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResourceAssemblyID {
            get {
                return this.ResourceAssemblyIDField;
            }
            set {
                if ((this.ResourceAssemblyIDField.Equals(value) != true)) {
                    this.ResourceAssemblyIDField = value;
                    this.RaisePropertyChanged("ResourceAssemblyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.Resource> Resources {
            get {
                return this.ResourcesField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourcesField, value) != true)) {
                    this.ResourcesField = value;
                    this.RaisePropertyChanged("Resources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.TranslationStatus WorstTranslationStatus {
            get {
                return this.WorstTranslationStatusField;
            }
            set {
                if ((this.WorstTranslationStatusField.Equals(value) != true)) {
                    this.WorstTranslationStatusField = value;
                    this.RaisePropertyChanged("WorstTranslationStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceAssembly", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    [System.SerializableAttribute()]
    public partial class ResourceAssembly : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastSyncDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.TranslationStatus WorstTranslationStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDateTime {
            get {
                return this.CreateDateTimeField;
            }
            set {
                if ((this.CreateDateTimeField.Equals(value) != true)) {
                    this.CreateDateTimeField = value;
                    this.RaisePropertyChanged("CreateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileFormat {
            get {
                return this.FileFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.FileFormatField, value) != true)) {
                    this.FileFormatField = value;
                    this.RaisePropertyChanged("FileFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastSyncDateTime {
            get {
                return this.LastSyncDateTimeField;
            }
            set {
                if ((this.LastSyncDateTimeField.Equals(value) != true)) {
                    this.LastSyncDateTimeField = value;
                    this.RaisePropertyChanged("LastSyncDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.TranslationStatus WorstTranslationStatus {
            get {
                return this.WorstTranslationStatusField;
            }
            set {
                if ((this.WorstTranslationStatusField.Equals(value) != true)) {
                    this.WorstTranslationStatusField = value;
                    this.RaisePropertyChanged("WorstTranslationStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BundleSyncStatus", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    public enum BundleSyncStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADDED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPDATED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REMOVED = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resource", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    [System.SerializableAttribute()]
    public partial class Resource : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BinaryValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DesignerSupportFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastChangeDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceBundle ResourceBundleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResourceBundleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResourceClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceSyncStatus ResourceSyncStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceType ResourceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceTranslation> TranslationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.TranslationStatus WorstTranslationStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BinaryValue {
            get {
                return this.BinaryValueField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaryValueField, value) != true)) {
                    this.BinaryValueField = value;
                    this.RaisePropertyChanged("BinaryValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDateTime {
            get {
                return this.CreateDateTimeField;
            }
            set {
                if ((this.CreateDateTimeField.Equals(value) != true)) {
                    this.CreateDateTimeField = value;
                    this.RaisePropertyChanged("CreateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DesignerSupportFlag {
            get {
                return this.DesignerSupportFlagField;
            }
            set {
                if ((this.DesignerSupportFlagField.Equals(value) != true)) {
                    this.DesignerSupportFlagField = value;
                    this.RaisePropertyChanged("DesignerSupportFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastChangeDateTime {
            get {
                return this.LastChangeDateTimeField;
            }
            set {
                if ((this.LastChangeDateTimeField.Equals(value) != true)) {
                    this.LastChangeDateTimeField = value;
                    this.RaisePropertyChanged("LastChangeDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceBundle ResourceBundle {
            get {
                return this.ResourceBundleField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceBundleField, value) != true)) {
                    this.ResourceBundleField = value;
                    this.RaisePropertyChanged("ResourceBundle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResourceBundleID {
            get {
                return this.ResourceBundleIDField;
            }
            set {
                if ((this.ResourceBundleIDField.Equals(value) != true)) {
                    this.ResourceBundleIDField = value;
                    this.RaisePropertyChanged("ResourceBundleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceClass {
            get {
                return this.ResourceClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceClassField, value) != true)) {
                    this.ResourceClassField = value;
                    this.RaisePropertyChanged("ResourceClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceSyncStatus ResourceSyncStatus {
            get {
                return this.ResourceSyncStatusField;
            }
            set {
                if ((this.ResourceSyncStatusField.Equals(value) != true)) {
                    this.ResourceSyncStatusField = value;
                    this.RaisePropertyChanged("ResourceSyncStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceType ResourceType {
            get {
                return this.ResourceTypeField;
            }
            set {
                if ((this.ResourceTypeField.Equals(value) != true)) {
                    this.ResourceTypeField = value;
                    this.RaisePropertyChanged("ResourceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceTranslation> Translations {
            get {
                return this.TranslationsField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslationsField, value) != true)) {
                    this.TranslationsField = value;
                    this.RaisePropertyChanged("Translations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.TranslationStatus WorstTranslationStatus {
            get {
                return this.WorstTranslationStatusField;
            }
            set {
                if ((this.WorstTranslationStatusField.Equals(value) != true)) {
                    this.WorstTranslationStatusField = value;
                    this.RaisePropertyChanged("WorstTranslationStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslationStatus", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    public enum TranslationStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_TRANSLATED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NEW = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CORRECT = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        APPROVED = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FINAL = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NO_NEED_TO_TRANSLATE = -1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceSyncStatus", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    public enum ResourceSyncStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADDED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPDATED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REMOVED = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceType", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    public enum ResourceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STRING = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STRING_ARRAY = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IMAGE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTHER_BINARY = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceTranslation", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    [System.SerializableAttribute()]
    public partial class ResourceTranslation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BinaryValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.Resource ResourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResourceAssemblyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResourceBundleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranslationByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TranslationDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.TranslationStatus TranslationStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BinaryValue {
            get {
                return this.BinaryValueField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaryValueField, value) != true)) {
                    this.BinaryValueField = value;
                    this.RaisePropertyChanged("BinaryValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Locale {
            get {
                return this.LocaleField;
            }
            set {
                if ((object.ReferenceEquals(this.LocaleField, value) != true)) {
                    this.LocaleField = value;
                    this.RaisePropertyChanged("Locale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.Resource Resource {
            get {
                return this.ResourceField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceField, value) != true)) {
                    this.ResourceField = value;
                    this.RaisePropertyChanged("Resource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResourceAssemblyID {
            get {
                return this.ResourceAssemblyIDField;
            }
            set {
                if ((this.ResourceAssemblyIDField.Equals(value) != true)) {
                    this.ResourceAssemblyIDField = value;
                    this.RaisePropertyChanged("ResourceAssemblyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResourceBundleID {
            get {
                return this.ResourceBundleIDField;
            }
            set {
                if ((this.ResourceBundleIDField.Equals(value) != true)) {
                    this.ResourceBundleIDField = value;
                    this.RaisePropertyChanged("ResourceBundleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResourceID {
            get {
                return this.ResourceIDField;
            }
            set {
                if ((this.ResourceIDField.Equals(value) != true)) {
                    this.ResourceIDField = value;
                    this.RaisePropertyChanged("ResourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranslationBy {
            get {
                return this.TranslationByField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslationByField, value) != true)) {
                    this.TranslationByField = value;
                    this.RaisePropertyChanged("TranslationBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TranslationDateTime {
            get {
                return this.TranslationDateTimeField;
            }
            set {
                if ((this.TranslationDateTimeField.Equals(value) != true)) {
                    this.TranslationDateTimeField = value;
                    this.RaisePropertyChanged("TranslationDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.TranslationStatus TranslationStatus {
            get {
                return this.TranslationStatusField;
            }
            set {
                if ((this.TranslationStatusField.Equals(value) != true)) {
                    this.TranslationStatusField = value;
                    this.RaisePropertyChanged("TranslationStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyncStatistics", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Sync")]
    [System.SerializableAttribute()]
    public partial class SyncStatistics : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddedAssembliesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddedBundlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddedResourcesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemovedBundlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemovedResourcesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpdatedBundlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpdatedResourcesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddedAssemblies {
            get {
                return this.AddedAssembliesField;
            }
            set {
                if ((this.AddedAssembliesField.Equals(value) != true)) {
                    this.AddedAssembliesField = value;
                    this.RaisePropertyChanged("AddedAssemblies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddedBundles {
            get {
                return this.AddedBundlesField;
            }
            set {
                if ((this.AddedBundlesField.Equals(value) != true)) {
                    this.AddedBundlesField = value;
                    this.RaisePropertyChanged("AddedBundles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddedResources {
            get {
                return this.AddedResourcesField;
            }
            set {
                if ((this.AddedResourcesField.Equals(value) != true)) {
                    this.AddedResourcesField = value;
                    this.RaisePropertyChanged("AddedResources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemovedBundles {
            get {
                return this.RemovedBundlesField;
            }
            set {
                if ((this.RemovedBundlesField.Equals(value) != true)) {
                    this.RemovedBundlesField = value;
                    this.RaisePropertyChanged("RemovedBundles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemovedResources {
            get {
                return this.RemovedResourcesField;
            }
            set {
                if ((this.RemovedResourcesField.Equals(value) != true)) {
                    this.RemovedResourcesField = value;
                    this.RaisePropertyChanged("RemovedResources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdatedBundles {
            get {
                return this.UpdatedBundlesField;
            }
            set {
                if ((this.UpdatedBundlesField.Equals(value) != true)) {
                    this.UpdatedBundlesField = value;
                    this.RaisePropertyChanged("UpdatedBundles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdatedResources {
            get {
                return this.UpdatedResourcesField;
            }
            set {
                if ((this.UpdatedResourcesField.Equals(value) != true)) {
                    this.UpdatedResourcesField = value;
                    this.RaisePropertyChanged("UpdatedResources");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TinyTranslatorApplicationServer.ITinyTranslatorResourceService")]
    public interface ITinyTranslatorResourceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorResourceService/GetProjects", ReplyAction="http://tempuri.org/ITinyTranslatorResourceService/GetProjectsResponse")]
        System.Collections.Generic.List<TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.Project> GetProjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorResourceService/GetResourceBundle", ReplyAction="http://tempuri.org/ITinyTranslatorResourceService/GetResourceBundleResponse")]
        TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceBundle GetResourceBundle(int bundleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorResourceService/SyncResourceAssembly", ReplyAction="http://tempuri.org/ITinyTranslatorResourceService/SyncResourceAssemblyResponse")]
        TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.SyncStatistics SyncResourceAssembly(TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceAssembly ra, System.Collections.Generic.List<TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceBundle> bundles);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITinyTranslatorResourceServiceChannel : TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ITinyTranslatorResourceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TinyTranslatorResourceServiceClient : System.ServiceModel.ClientBase<TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ITinyTranslatorResourceService>, TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ITinyTranslatorResourceService {
        
        public TinyTranslatorResourceServiceClient() {
        }
        
        public TinyTranslatorResourceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TinyTranslatorResourceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TinyTranslatorResourceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TinyTranslatorResourceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.Project> GetProjects() {
            return base.Channel.GetProjects();
        }
        
        public TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceBundle GetResourceBundle(int bundleID) {
            return base.Channel.GetResourceBundle(bundleID);
        }
        
        public TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.SyncStatistics SyncResourceAssembly(TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceAssembly ra, System.Collections.Generic.List<TinyTranslatorSyncAssemblyClient.TinyTranslatorApplicationServer.ResourceBundle> bundles) {
            return base.Channel.SyncResourceAssembly(ra, bundles);
        }
    }
}
