//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    [System.SerializableAttribute()]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectLocaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.ProjectLocale> TranslationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectLocale {
            get {
                return this.ProjectLocaleField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectLocaleField, value) != true)) {
                    this.ProjectLocaleField = value;
                    this.RaisePropertyChanged("ProjectLocale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.ProjectLocale> Translations {
            get {
                return this.TranslationsField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslationsField, value) != true)) {
                    this.TranslationsField = value;
                    this.RaisePropertyChanged("Translations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectLocale", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    [System.SerializableAttribute()]
    public partial class ProjectLocale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocaleCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocaleCode {
            get {
                return this.LocaleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocaleCodeField, value) != true)) {
                    this.LocaleCodeField = value;
                    this.RaisePropertyChanged("LocaleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceAssembly", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    [System.SerializableAttribute()]
    public partial class ResourceAssembly : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastSyncDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.TranslationStatus WorstTranslationStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDateTime {
            get {
                return this.CreateDateTimeField;
            }
            set {
                if ((this.CreateDateTimeField.Equals(value) != true)) {
                    this.CreateDateTimeField = value;
                    this.RaisePropertyChanged("CreateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileFormat {
            get {
                return this.FileFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.FileFormatField, value) != true)) {
                    this.FileFormatField = value;
                    this.RaisePropertyChanged("FileFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastSyncDateTime {
            get {
                return this.LastSyncDateTimeField;
            }
            set {
                if ((this.LastSyncDateTimeField.Equals(value) != true)) {
                    this.LastSyncDateTimeField = value;
                    this.RaisePropertyChanged("LastSyncDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.TranslationStatus WorstTranslationStatus {
            get {
                return this.WorstTranslationStatusField;
            }
            set {
                if ((this.WorstTranslationStatusField.Equals(value) != true)) {
                    this.WorstTranslationStatusField = value;
                    this.RaisePropertyChanged("WorstTranslationStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslationStatus", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    public enum TranslationStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_TRANSLATED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NEW = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CORRECT = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IMPORTED = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        APPROVED = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FINAL = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NO_NEED_TO_TRANSLATE = -1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceSyncStatistics", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    [System.SerializableAttribute()]
    public partial class ResourceSyncStatistics : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddedAssembliesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddedBundlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddedResourcesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemovedBundlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemovedResourcesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpdatedBundlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpdatedResourcesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddedAssemblies {
            get {
                return this.AddedAssembliesField;
            }
            set {
                if ((this.AddedAssembliesField.Equals(value) != true)) {
                    this.AddedAssembliesField = value;
                    this.RaisePropertyChanged("AddedAssemblies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddedBundles {
            get {
                return this.AddedBundlesField;
            }
            set {
                if ((this.AddedBundlesField.Equals(value) != true)) {
                    this.AddedBundlesField = value;
                    this.RaisePropertyChanged("AddedBundles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddedResources {
            get {
                return this.AddedResourcesField;
            }
            set {
                if ((this.AddedResourcesField.Equals(value) != true)) {
                    this.AddedResourcesField = value;
                    this.RaisePropertyChanged("AddedResources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemovedBundles {
            get {
                return this.RemovedBundlesField;
            }
            set {
                if ((this.RemovedBundlesField.Equals(value) != true)) {
                    this.RemovedBundlesField = value;
                    this.RaisePropertyChanged("RemovedBundles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemovedResources {
            get {
                return this.RemovedResourcesField;
            }
            set {
                if ((this.RemovedResourcesField.Equals(value) != true)) {
                    this.RemovedResourcesField = value;
                    this.RaisePropertyChanged("RemovedResources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdatedBundles {
            get {
                return this.UpdatedBundlesField;
            }
            set {
                if ((this.UpdatedBundlesField.Equals(value) != true)) {
                    this.UpdatedBundlesField = value;
                    this.RaisePropertyChanged("UpdatedBundles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdatedResources {
            get {
                return this.UpdatedResourcesField;
            }
            set {
                if ((this.UpdatedResourcesField.Equals(value) != true)) {
                    this.UpdatedResourcesField = value;
                    this.RaisePropertyChanged("UpdatedResources");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslationSyncStatistics", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.Model")]
    [System.SerializableAttribute()]
    public partial class TranslationSyncStatistics : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddedTranslationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExistingTranslationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResourceMismatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResourceNotFoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnchangedResourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddedTranslations {
            get {
                return this.AddedTranslationsField;
            }
            set {
                if ((this.AddedTranslationsField.Equals(value) != true)) {
                    this.AddedTranslationsField = value;
                    this.RaisePropertyChanged("AddedTranslations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExistingTranslations {
            get {
                return this.ExistingTranslationsField;
            }
            set {
                if ((this.ExistingTranslationsField.Equals(value) != true)) {
                    this.ExistingTranslationsField = value;
                    this.RaisePropertyChanged("ExistingTranslations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResourceMismatch {
            get {
                return this.ResourceMismatchField;
            }
            set {
                if ((this.ResourceMismatchField.Equals(value) != true)) {
                    this.ResourceMismatchField = value;
                    this.RaisePropertyChanged("ResourceMismatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResourceNotFound {
            get {
                return this.ResourceNotFoundField;
            }
            set {
                if ((this.ResourceNotFoundField.Equals(value) != true)) {
                    this.ResourceNotFoundField = value;
                    this.RaisePropertyChanged("ResourceNotFound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnchangedResource {
            get {
                return this.UnchangedResourceField;
            }
            set {
                if ((this.UnchangedResourceField.Equals(value) != true)) {
                    this.UnchangedResourceField = value;
                    this.RaisePropertyChanged("UnchangedResource");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslationSelection", Namespace="http://schemas.datacontract.org/2004/07/TinyTranslatorApplicationServer.DAL")]
    [System.SerializableAttribute()]
    public partial class TranslationSelection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssemblyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BundleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ResourceIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssemblyID {
            get {
                return this.AssemblyIDField;
            }
            set {
                if ((this.AssemblyIDField.Equals(value) != true)) {
                    this.AssemblyIDField = value;
                    this.RaisePropertyChanged("AssemblyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BundleID {
            get {
                return this.BundleIDField;
            }
            set {
                if ((this.BundleIDField.Equals(value) != true)) {
                    this.BundleIDField = value;
                    this.RaisePropertyChanged("BundleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Locale {
            get {
                return this.LocaleField;
            }
            set {
                if ((object.ReferenceEquals(this.LocaleField, value) != true)) {
                    this.LocaleField = value;
                    this.RaisePropertyChanged("Locale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ResourceID {
            get {
                return this.ResourceIDField;
            }
            set {
                if ((this.ResourceIDField.Equals(value) != true)) {
                    this.ResourceIDField = value;
                    this.RaisePropertyChanged("ResourceID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TinyTranslatorImportExportService.ITinyTranslatorImportExportService")]
    public interface ITinyTranslatorImportExportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorImportExportService/GetProjects", ReplyAction="http://tempuri.org/ITinyTranslatorImportExportService/GetProjectsResponse")]
        System.Collections.Generic.List<TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.Project> GetProjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorImportExportService/GetResourceAssembliesByProj" +
            "ect", ReplyAction="http://tempuri.org/ITinyTranslatorImportExportService/GetResourceAssembliesByProj" +
            "ectResponse")]
        System.Collections.Generic.List<TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.ResourceAssembly> GetResourceAssembliesByProject(int projectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorImportExportService/ImportResourceFromAssembly", ReplyAction="http://tempuri.org/ITinyTranslatorImportExportService/ImportResourceFromAssemblyR" +
            "esponse")]
        TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.ResourceSyncStatistics ImportResourceFromAssembly(System.IO.Stream assemblyStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorImportExportService/ImportTranslationsFromCsv", ReplyAction="http://tempuri.org/ITinyTranslatorImportExportService/ImportTranslationsFromCsvRe" +
            "sponse")]
        TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.TranslationSyncStatistics ImportTranslationsFromCsv(System.IO.Stream csvFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorImportExportService/ExportTranslationsToCsv", ReplyAction="http://tempuri.org/ITinyTranslatorImportExportService/ExportTranslationsToCsvResp" +
            "onse")]
        System.IO.Stream ExportTranslationsToCsv(TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.TranslationSelection translations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorImportExportService/ImportTranslationsFromAssem" +
            "bly", ReplyAction="http://tempuri.org/ITinyTranslatorImportExportService/ImportTranslationsFromAssem" +
            "blyResponse")]
        TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.TranslationSyncStatistics ImportTranslationsFromAssembly(System.IO.Stream assemblyStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyTranslatorImportExportService/ExportTranslationsToAssembl" +
            "y", ReplyAction="http://tempuri.org/ITinyTranslatorImportExportService/ExportTranslationsToAssembl" +
            "yResponse")]
        System.IO.Stream ExportTranslationsToAssembly(int resourceAssemblyID, string locale);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITinyTranslatorImportExportServiceChannel : TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.ITinyTranslatorImportExportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TinyTranslatorImportExportServiceClient : System.ServiceModel.ClientBase<TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.ITinyTranslatorImportExportService>, TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.ITinyTranslatorImportExportService {
        
        public TinyTranslatorImportExportServiceClient() {
        }
        
        public TinyTranslatorImportExportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TinyTranslatorImportExportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TinyTranslatorImportExportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TinyTranslatorImportExportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.Project> GetProjects() {
            return base.Channel.GetProjects();
        }
        
        public System.Collections.Generic.List<TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.ResourceAssembly> GetResourceAssembliesByProject(int projectID) {
            return base.Channel.GetResourceAssembliesByProject(projectID);
        }
        
        public TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.ResourceSyncStatistics ImportResourceFromAssembly(System.IO.Stream assemblyStream) {
            return base.Channel.ImportResourceFromAssembly(assemblyStream);
        }
        
        public TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.TranslationSyncStatistics ImportTranslationsFromCsv(System.IO.Stream csvFile) {
            return base.Channel.ImportTranslationsFromCsv(csvFile);
        }
        
        public System.IO.Stream ExportTranslationsToCsv(TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.TranslationSelection translations) {
            return base.Channel.ExportTranslationsToCsv(translations);
        }
        
        public TinyTranslatorExportTranslationsClient.TinyTranslatorImportExportService.TranslationSyncStatistics ImportTranslationsFromAssembly(System.IO.Stream assemblyStream) {
            return base.Channel.ImportTranslationsFromAssembly(assemblyStream);
        }
        
        public System.IO.Stream ExportTranslationsToAssembly(int resourceAssemblyID, string locale) {
            return base.Channel.ExportTranslationsToAssembly(resourceAssemblyID, locale);
        }
    }
}
